[package]
name = "rs-raytracer"
version = "0.1.0"
authors = ["Omer Ben-Amram <omerbenamram@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.22.1"
num-traits = "0.2.8"
num = "0.2.0"
rand = "0.7.0"
rayon = "1.1.0"
indicatif = "0.11.0"
clap = "2.33.0"